name: Promote Local
favicon: null
layout_spectrum: 0.33798500755801797
typography_spectrum: 0.8810148132033646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7386755892075598
  lightness: 0.33121168310754
  saturation: 0.8703993835952133
  rhythmicContrast: 0.25610306998714805
purpose: []
