name: Promote Local
favicon: null
layout_spectrum: 0.33798500755801797
typography_spectrum: 0.57279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ad58a2'
    - '#ffffff'
    - '#c97cb4'
    - '#ead7e6'
    - '#e0bcd5'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
