name: Promote Local
favicon: null
layout_spectrum: 0.33798500755801797
typography_spectrum: 0.57279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b15ea4'
    - '#a8a9ad'
    - '#f4f4f4'
    - '#aa96aa'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
